### ISSUE TITLE
Reconciliation workflow

### ISSUE THREAD

**Issue by cransom12** [danielkeller/budge_it#42]
- Aim: match online banking account balance with budge-it balance
- Clear items, add missing transactions
- When balances match, hit save

**Comment by danielkeller** [comment]
Mostly done. Only needs edit protection

**Comment by danielkeller** [comment]
Idea for edit protection: The regular account is for the unreconciled amount, and there is another hidden account for the reconciled amount. When you hit reconcile, an entry is added from the unreconciled to reconciled accounts. This entry isn't touched by any other operation, even deletion.
