### ISSUE TITLE
Don't reset the calendar to today's date after quick adding something

### ISSUE THREAD

**Issue by TedTed** [danielkeller/budge_it#46]
I go through expenses in chronological (or reverse chronological) order, so it'd be convenient not to have to change the date for multiple expenses on the same day, and to only have to change the day for most other expenses (if I budget at the beginning of the month, most of my expenses are going to be from the previous month, so I have to change the month every time). Instead, having the date default to "previous date used" would be nice.

**Comment by danielkeller** [comment]
I'll try having the date reset to the date of the most recently selected transaction. Maybe even making the "adder row" move above the selection would be nice.

**Comment by danielkeller** [comment]
Fixed by 27f98c69.
