### ISSUE TITLE
Bulk transaction edit

### ISSUE THREAD

**Issue by cransom12** [danielkeller/budge_it#60]
- Moving
- Merging
- Show totals

**Comment by danielkeller** [comment]
An idea for this:

When you select multiple transactions, you get an editor with no date, repeat, or memos, and one part. The header says "[n] transactions selected". The part editor shows every entry of the transactions, summed together by account/category/payee etc. The amounts (or at least amounts that come from multiple transaction parts) are not editable and you can't add new entries. But the accounts, categories, and payees are editable and the edit changes all the transactions with that account/category.

This conveniently shows totals as well. Also maybe a merge button. I think it should group the parts by memo.

**Comment by danielkeller** [comment]
Also, drag and drop for transactions, which substitutes current account -> dropped account. Would replace "move here" as well.

**Comment by danielkeller** [comment]
Done.
